export const searchLaptop = [
  'Apple',
  'Dell',
  'HP',
  'Lenovo',
  'Asus',
  'Acer',
  'Microsoft',
  'Samsung',
  'MSI',
  'Razer',
  'LG',
  'Huawei',
  'Sony',
  'Toshiba',
  'Fujitsu',
  'Alienware',
  'Google',
  'MacBook Pro',
  'Inspiron',
  'Pavilion',
  'ThinkPad',
  'ZenBook',
  'Swift',
  'Surface Laptop',
  'Galaxy Book',
  'GS Series',
  'Blade',
  'Gram',
  'MateBook',
  'VAIO',
  'Portégé',
  'LifeBook',
  'Alienware',
  'Pixelbook',
  'Intel Core i3',
  'Intel Core i5',
  'Intel Core i7',
  'Intel Core i9',
  'AMD Ryzen 3',
  'AMD Ryzen 5',
  'AMD Ryzen 7',
  '4GB RAM',
  '8GB RAM',
  '16GB RAM',
  '32GB RAM',
  '64GB RAM',
  '256GB SSD',
  '512GB SSD',
  '1TB SSD',
  '2TB SSD',
  'HDD options available',
  '13-inch',
  '14-inch',
  '15-inch',
  '17-inch',
  '4K resolution',
  'Integrated Intel UHD Graphics',
  'NVIDIA GeForce GTX 1650',
  'NVIDIA GeForce RTX 3060',
  'AMD Radeon RX 5500M',
  'AMD Radeon RX Vega',
  'Windows 10 Home',
  'Windows 10 Pro',
  'macOS',
  'Linux',
];
